# Node Image for docker on which code will execute
image: node:latest

# This is the stages / task to perfom in jobs
stages:
  - build
  - deploy

# This command is run before the execution of stages
before_script:
  - npm install --force

# Making build for main
build_main:
  stage: build
  script:
    - npm run build
  only: ['master']
  artifacts:
    paths:
      - dist/

# Job Two for deploy build to S3 for main
deploy_main:
  environment:
    name: main
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - ls -lash
    #- aws s3 sync ./dist/ui ${BUCKET_S3} --delete
    #- aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION_ID} --paths "/*" 
  only: ['main']
